name: Wheels

on:
  workflow_run:
    workflows: [Lint, MyPy, PyTest]
    types: [completed]

jobs:
  wheels:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [lint, mypy, pytest]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build
        run: |
          pip install cibuildwheel
          cibuildwheel --output-dir dist
      - name: Build source dist
        run: python -m build . --sdist
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist