name: Wheels

on: workflow_call

jobs:
  wheels_lint:
    uses: ./.github/workflows/black.yml
  wheels_mypy:
    uses: ./.github/workflows/mypy.yml
  wheels_pytest:
    uses: ./.github/workflows/pytest.yml
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [wheels_lint, wheels_mypy, wheels_pytest]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.2

      - uses: actions/upload-artifact@v4
        with:
          name: pyhaloxml-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    needs: [wheels_lint, wheels_mypy, wheels_pytest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: pyhaloxml-sdist
          path: dist/*.tar.gz
